### ISSUE TITLE
The setup.py file is pulling an incomplete version of the API

### ISSUE THREAD

**Issue by Ethan1498** [pseudonym117/Riot-Watcher#143]
When running setup.py, it creates a folder which is missing the files LolWatcher.py etc...

**Comment by pseudonym117** [comment]
What command are you using to install?

**Comment by Ethan1498** [comment]
pip3 install riotwatcher

**Comment by pseudonym117** [comment]
Ah, that is because the currently released version on PyPi is actually this version: https://github.com/pseudonym117/Riot-Watcher/tree/v2.7.1

Current changes on master are not yet pushed, as I plan to make a few more changes before pushing version 3.0.0. 

I should update the readthedocs page to have a `stable` and `latest` tag though... will look into updating that to have another tag.

**Comment by afDeathscythe** [comment]
Got the same problem now - which branch shall we download now? :)

**Comment by Ethan1498** [comment]
Just copy the /src folder from this repo into your src folder and that should work

**Comment by pseudonym117** [comment]
Plz don't do that. If you want the latest code and don't care that API may break, then clone this repo and run `pip install .`

If you want the supported version, then use the documentation version linked above, and keep using `pip install riotwatcher `

**Comment by pseudonym117** [comment]
Docs page generated for the most recently published version here: https://riot-watcher.readthedocs.io/en/v2.7.1/

New version based on master should come soon (tm), I believe theres only 1 more change I want to make before publishing.
