### ISSUE TITLE
API out of date

### ISSUE THREAD

**Issue by 15ealbino** [pseudonym117/Riot-Watcher#71]
So on July 24, this API will be outdated, does anyone know how to change the version?

**Comment by erickseolin** [comment]
I am working on a update for the version 3 of the API:
[Riot Watcher](https://github.com/erickseolin/Riot-Watcher)
I hope to finish it soon.

**Comment by 15ealbino** [comment]
Thank you for your work.

**Comment by pseudonym117** [comment]
I'm also working on updating the main repo to use the v3 apis. The work for just the v3 migration is almost done. But since the api can't be fully backwards compatible (due to riot removing bulk queries), I'm using this as an opportunity to make different improvements that are breaking changes. 

If I manage to pull it off, it should add support for user defined caching and rate limiting, throughout the entire api, with some default implementations that make sense.

**Comment by i32ropie** [comment]
Hi @pseudonym117 How is the update going? If you want me to help you with the update you can chat to me at Telegram, my username is [@Edurolp](https://t.me/edurolp)

Btw, I just got this message from RIOT tonight:
![image](https://user-images.githubusercontent.com/9365723/27577314-8624c058-5b20-11e7-9101-929561132eed.png)
So if I can help you just tell me, I like your wrapper and I use it in my Telegram bot [@LoL_bot](https://t.me/lol_bot)

Good luck with the update! :1

**Comment by pseudonym117** [comment]
experimental version of API update is pushed to branch api_v3_experimental. API changes are unfortunately breaking, but i am working on a backwards compatibility wrapper as i type this that will hopefully make the transition a bit less painful.

After finishing the backwards compatibility wrapper and double checking that all method names make sense, i will merge this branch to master and upload the project to pypi. likely will be done monday or tuesday.

**Comment by pseudonym117** [comment]
fixed as of 54f3291
